### ISSUE TITLE
Email iframe and links

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/breeze#31]
Clicking on a link in the email iframe goes to the link from within the iframe. Not sure if this was done intentionally.

I believe the desire to use iframes was so that it could be styled without breeze styling messing it up

**Comment by jwoertink** [comment]
Yeah, exactly. The iframe was used because a lot of email templates include the doctype and the whole body, plus you don't want the breeze styles to conflict.

The links would probably need to have a `target="_blank"` added to make them open in a new tab. Not sure how we could do that from the Breeze side though 🤔
